# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Notredame-Api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run tests with coverage
      run: dotnet test --logger trx --collect:"XPlat Code Coverage" --results-directory .${{github.workspace}}/report/
    - name: Install ReportGenerator tool
      run: dotnet tool install dotnet-reportgenerator-globaltool --global
    - name: Generate coverage report
      run: reportgenerator -reports:.${{github.workspace}}/report/**/*.xml -targetdir:${{github.workspace}}/report -reporttypes:MarkdownSummary
    - name: Add Coverage PR Comment
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automated report generation: $REPORT_DATE"
        files: .${{github.workspace}}/report/MarkdownSummary.md
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
